title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Ideas
        Have an idea to improve Pluginator? We'd love to hear it!

        For bug reports, please use [Issues](https://github.com/NindroidA/pluginator/issues/new?template=bug_report.md) instead.

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your feature idea
      placeholder: It would be great if Pluginator could...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful? How would you use it?
      placeholder: This would help me because...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternatives?
      placeholder: Currently I work around this by...
    validations:
      required: false
