title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Show and Tell
        Share your Pluginator setup, themes, or cool configurations!

        This is a great place to:
        - Share your plugin management workflow
        - Show off custom configurations
        - Share tips and tricks you've discovered

  - type: textarea
    id: showcase
    attributes:
      label: What are you sharing?
      description: Tell us about your setup or workflow
      placeholder: |
        I've set up Pluginator to manage my network of servers...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Any configuration snippets, screenshots, or additional details
      placeholder: |
        Here's my plugins.json configuration...
    validations:
      required: false

  - type: textarea
    id: tips
    attributes:
      label: Tips for Others
      description: Any tips you'd share with other users?
      placeholder: One thing I learned was...
    validations:
      required: false
