name: Bug Report
description: Report a bug or unexpected behavior in Pluginator
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for taking the time to report a bug! Please fill out the form below
        to help us understand and fix the issue.

  - type: input
    id: version
    attributes:
      label: Pluginator Version
      description: What version of Pluginator are you using?
      placeholder: "e.g., 1.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running Pluginator on?
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (x64)
        - Linux (ARM)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Run `pluginator`
        2. Press '...'
        3. Select '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: |
        Include any error messages or relevant log output.
        Logs are stored in `~/.pluginator/logs/`
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Any other context about the problem?
        - Screenshots
        - Your server setup (Paper, Spigot, etc.)
        - Number of plugins

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of Pluginator
          required: false
